#  This is manual page in Perl POD format. Read more at
#  http://perldoc.perl.org/perlpod.html or run command:
#
#     perldoc perlpod | less
#
#  To check the syntax:
#
#     podchecker *.pod
#
#  Create manual page with command:
#
#    pod2man PAGE.N.pod > PAGE.N

=pod

=head1 NAME

rt2html-htdig - Convert RTF files to HTML

=head1 SYNOPSIS

  rt2html-htdig file.rtf > file.html

=head1 DESCRIPTION

Utility to convert RTF files into simple HTML files

=head1 OPTIONS

None.

=head1 ENVIRONMENT

None.

=head1 FILES

None.

=head1 SEE ALSO

C<pdf2html(1)>

=head1 AUTHORS

This manual page was created by package maintainer for Cygwin system
(but may be used by others) because the original package did not
include one.

=cut
